# Generated by Django 4.2.1 on 2023-05-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_Id", models.IntegerField(primary_key=True, serialize=False)),
                ("DOB", models.DateField()),
                ("Gender", models.CharField(max_length=1)),
                ("city_code", models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("customer_id", models.IntegerField()),
                ("transaction_date", models.DateField()),
                ("product_subcat_code", models.IntegerField()),
                ("product_cat_code", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("rate", models.FloatField()),
                ("tax", models.FloatField()),
                ("total_amt", models.FloatField()),
                ("store_type", models.CharField(max_length=20)),
            ],
        ),
    ]
