# Generated by Django 4.2.1 on 2023-05-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("segmentation", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
