# Generated by Django 4.2.1 on 2023-05-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
