# Generated by Django 4.2.1 on 2023-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_order_date_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateField(default="2014-02-20"),
        ),
    ]
