# Generated by Django 4.2.1 on 2023-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_transaction_id_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
