# Generated by Django 4.2.1 on 2023-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
